allowBuilds:
  esbuild: true
  sharp: false
  workerd: true

minimumReleaseAge: 1440

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
